verifyDepsBeforeRun: install
packages:
  - "packages/*"
  - "docs/**"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.21-alpha.7
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.21-alpha.7
  vite-plus: 0.1.21-alpha.7
  esbuild: ^0.28.0
  typescript: ^6.0.2
  react: ^19.2.5
  react-dom: ^19.2.5
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/node": ^25.6.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
